### ISSUE TITLE
the extension does not work.

### ISSUE THREAD

**Issue by CMQNordic** [ElecTreeFrying/drag-import-relative-path#2]
Only full path C:/blbla/file.cc is pased in on shift drop.

Tried diffrent setting. Doeas not work

**Comment by ElecTreeFrying** [comment]
Hi, looks like you're dragging a `.cc` file type.
[These](https://github.com/ElecTreeFrying/drag-import-relative-path#supported-file-extensions) are the supported file types the extension can handle for now.
