### ISSUE TITLE
Errors-out: Same file path

### ISSUE THREAD

**Issue by dfdumaresq** [ElecTreeFrying/drag-import-relative-path#3]
When I try dropping the .scss file I want to import into my .tsx file. I see the message `Same file path`.
What's the issue I'm missing?

![image](https://user-images.githubusercontent.com/20051/207441246-f4ccc137-d043-4c13-b43e-ee98e3db36a5.png)

Would love to get this to work! Thanks!

**Comment by ElecTreeFrying** [comment]
Currently, the extension doesn't support dragging and dropping .css/.scss files to .tsx/.jsx files. I will work on this new feature this month and will update you when it is ready.

**Comment by adrianabelarde** [comment]
any progress on this issue? I just recently found this out. @ElecTreeFrying

**Comment by ElecTreeFrying** [comment]
@dfdumaresq @drianlarde Hey everyone, just wanted to let you know that a new version of this feature is now available. Make sure to update the extension to check it out! Thanks for using it and for your feedback.
