### ISSUE TITLE
Same file path Issue when i drag a js file into head

### ISSUE THREAD

**Issue by banmtG** [ElecTreeFrying/drag-import-relative-path#7]
![image](https://github.com/ElecTreeFrying/drag-import-relative-path/assets/6801006/7628ad82-36fb-4215-acaf-ba6e109dc5bd)

Botton right. The notification said Same File path and nothing was imported as other script links in the head section.

Please help!

**Comment by ElecTreeFrying** [comment]
Hi, I have just published a new release to fix a bug for this issue. Kindly update the extension and reload or restart the VSCode editor. Thank you.

**Comment by banmtG** [comment]
Thanks. It works perfectly now!

**Comment by ElecTreeFrying** [comment]
Glad to hear that! Thank you for posting regarding your issue. If you have any feature requests or suggestions, please let me know by opening another issue. Cheers.
