### ISSUE TITLE
Looks great... but using it?

### ISSUE THREAD

**Issue by chrispopp8** [ElecTreeFrying/drag-import-relative-path#8]
I've installed the extension, restarted my Visual Studio Code 2023 and... the links don't appear when doing shift + drag. 

The expected outcome is when I'm editing a .htm or .php file and I want to make a hyperlink I would just grab my filename from the list on the left, hold shift, and drag it to where I want to place the link. 

<a href="link.htm">example

Instead I get the standard result with VS Code:

link,.htmexample

As you can see, the tag isn't generated. 

Extension  is installed and activated. Not sure if there's additional steps, key strokes, etc. to use above what is provided. If there's something that needs to be done in settings somewhere, I have no idea what. 

Granted, my experience with VS Code is about a year or so... but I am sure there's others like me who don't "just know" what to do.

Any advice, links to video tuts, etc. would be helpful.

Mahalo

**Comment by ElecTreeFrying** [comment]
Hi, thank you for using the extension. Currently, the extension only supports a limited number of file types for drag-and-drop import with relative paths. Below, I have listed the supported file types that the extension currently supports.

| Active text editor <br> Drop (to) | Supported file extensions <br> Drag (from)                                                                                                                                |
| :-------------------------------: | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|              `.html`              | `.js`, `.css`, `.gif`, `.jpeg`, `.jpg`, `.png`, .`webp`                                                                                                                   |
|               `.md`               | self, `.gif`, `.jpeg`, `.jpg`, `.png`, .`webp`                                                                                                                            |
|           `.js`, `.ts`            | self                                                                                                                                                                      |
|              `.jsx`               | self, `.js`, `.json`<br>`.css`,`.sass` `.scss`<br>`.png`, `.jpg`, `.gif`, `.svg`, `.webp`<br>`.woff`, `.woff2`, `.ttf`, `.eot`<br>`.md`, `.yml`, `.yaml`, `.html`         |
|              `.tsx`               | self, `.ts`, `.js`, `.json`<br>`.css`, `.sass` `.scss`<br>`.png`, `.jpg`, `.gif`, `.svg`, `.webp`<br>`.woff`, `.woff2`, `.ttf`, `.eot`<br>`.md`, `.yml`, `.yaml`, `.html` |
|              `.css`               | self, `.gif`, `.jpeg`, `.jpg`, `.png`, .`webp`                                                                                                                            |
|              `.scss`              | self,  `.css`, `.gif`, `.jpeg`, `.jpg`, `.png`, .`webp`                                                                                                                   |
